from typing import Protocol

from app.domain.entities import Actor

class FollowRepo(Protocol):
    async def exists(self, follower_id: str, followed_id: str) -> bool: ...
    def add(self, follower_id: str, followed_id: str) -> None: ...
    async def remove(self, follower_id: str, followed_id: str) -> None: ...
    async def followers(self, actor_id: str) -> list[Actor]: ...
    async def following(self, actor_id: str) -> list[Actor]: ...
    async def local_follower_ids(self, actor_id: str) -> list[str]: ...