from typing import Protocol

from app.domain.entities import Note

class TimelineRepo(Protocol):
    async def add(self, entries: list[dict]) -> None: ...
    async def remove_author(self, owner_id: str, author_id:str) -> None: ...
    async def home(self, owner_id: str, limit: int) -> list[None]: ...